# Generated by Django 4.2.4 on 2024-05-20 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Category name')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_pics', verbose_name='Property image')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Location name')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tag name')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Property name')),
                ('price', models.BigIntegerField(verbose_name='Price of the property')),
                ('place', models.CharField(max_length=250, verbose_name='Where property is located')),
                ('street', models.CharField(max_length=150, verbose_name='Street in which proerty located')),
                ('bedrooms', models.PositiveIntegerField(verbose_name='No of bed rooms in the property')),
                ('baths', models.PositiveIntegerField(verbose_name='No of baths in the property')),
                ('category', models.ManyToManyField(blank=True, to='rentifyV1.category')),
                ('images', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rentifyV1.image')),
                ('like', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rentifyV1.location')),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prop_seller', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='rentifyV1.tag')),
                ('wishlist', models.ManyToManyField(blank=True, related_name='whishlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
