# Generated by Django 4.2.4 on 2024-05-20 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentifyV1', '0002_alter_property_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='images',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentifyV1.image'),
        ),
    ]
