# Generated by Django 4.2.4 on 2024-05-29 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentifyV1', '0003_alter_property_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='tags',
            new_name='amenities',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='name',
            new_name='property_name',
        ),
    ]
